CREATE TABLE SHIPWRECK(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  CONDITION VARCHAR(255),
  DEPTH INTEGER,
  LATITUDE FLOAT ,
  LONGITUDE FLOAT,
  YEAR_DISCOVERED INTEGER
);