version: '3'

services:
  db:
    build: .
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: dasboot

